language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - mysql
env:
  -DJANGO:2.0.3 DB=mysql
before_script:
  - pip install -r requirements/*
  - mysql -e 'create database test;' -u root
script:
  - python manage.py test
